# SPDX-License-Identifier: MIT
"""Wiring: collectors -> model -> selection -> `RunResult`.

The whole run in one function, so `--fixtures` and a live run differ only in which `Transport` is
constructed. Nothing here decides anything about the launch set; it resolves the block window,
calls each collector in dependency order, and hands the result to `model` and `selection`.
"""

from __future__ import annotations

from pathlib import Path

from .collectors.apis import ApiCrossCheckCollector
from .collectors.base import RunContext, all_hosts
from .collectors.feeds import FeedCollector
from .collectors.market import MarketCollector
from .collectors.pools import PoolCollector
from .collectors.universe import TokenUniverseCollector
from .config import RunParams
from .inclusion import compute_inclusion
from .model import build_metrics
from .results import RunResult
from .rpc import JsonRpc, load_endpoints
from .selection import select
from .transport import FixtureTransport, HttpTransport, Transport

#: The cassette shipped with the package: synthetic, generated by tools/generate_fixtures.py.
DEFAULT_CASSETTE = Path(__file__).parent / "fixtures" / "cassette.json"


def build_transport(params: RunParams, cassette: Path | None = None) -> Transport:
    """The transport a run should use: the cassette under `--fixtures`, else real HTTP."""
    if params.fixtures:
        return FixtureTransport.from_path(cassette or DEFAULT_CASSETTE)
    return HttpTransport(timeout=params.timeout, retries=params.retries)


def run(
    params: RunParams,
    *,
    transport: Transport | None = None,
    cassette: Path | None = None,
    api_delay_seconds: float = 2.0,
    strict_universe: bool = False,
    log: object = None,
) -> RunResult:
    """Execute one full pipeline run."""

    def say(message: str) -> None:
        if callable(log):
            log(message)

    transport = transport or build_transport(params, cassette)
    rpc = JsonRpc(transport=transport, endpoints=load_endpoints(params.rpc_url, params.fallback_rpc_url))

    head_block = rpc.block_number()
    head_ts = rpc.block_timestamp(head_block)
    window_from = rpc.block_at_timestamp(head_ts - params.window_days * 86_400, head=head_block)
    short_from = rpc.block_at_timestamp(head_ts - params.short_window_days * 86_400, head=head_block)
    say(
        f"head block {head_block:,} at {head_ts}; window from {window_from:,}"
        f" ({params.window_days}d), short from {short_from:,} ({params.short_window_days}d)"
    )

    ctx = RunContext(
        transport=transport,
        params=params,
        rpc=rpc,
        now_ts=head_ts,
        head_block=head_block,
        window_from_block=window_from,
        short_from_block=short_from,
    )

    universe = TokenUniverseCollector(strict=strict_universe)
    pools = PoolCollector()
    market = MarketCollector()
    feeds = FeedCollector()
    apis = ApiCrossCheckCollector(delay_seconds=api_delay_seconds)

    tokens = universe.collect(ctx)
    say(f"universe: {len(tokens)} stock tokens")

    pool_set = pools.collect_for(ctx, tokens)
    say(f"pools: {len(pool_set.all_pools)} across {len(pool_set.by_token)} tokens")

    markets = market.collect_for(ctx, pool_set, {t.key: t for t in tokens})
    say(f"markets: {sum(len(v) for v in markets.values())} measured")

    feed_map = feeds.collect(ctx)
    say(f"feeds: {len(feed_map)} standard USD feeds")

    quotes = apis.collect_for(ctx, tokens)

    metrics, quartiles = build_metrics(tokens, markets, feed_map, quotes, params)
    selection = select(metrics, params)
    inclusion = compute_inclusion([c.metrics for c in selection.chosen])
    say(f"selected {len(selection.chosen)} of {params.count}")

    return RunResult(
        params=params,
        metrics=metrics,
        selection=selection,
        inclusion=inclusion,
        sources=ctx.sources,
        warnings=ctx.warnings + rpc.warnings,
        quartiles=quartiles,
        data_timestamp=head_ts,
        head_block=head_block,
        window_from_block=window_from,
        short_from_block=short_from,
        rpc_requests=rpc.request_count,
        log_requests=rpc.log_request_count,
        hosts=all_hosts([universe, pools, market, feeds, apis]),
    )
