# SPDX-License-Identifier: MIT
"""The Markdown report: `docs/launch-constituents.md`.

Written for someone who has to defend the launch set, not for someone who already believes it. The
order is: what this run measured, how the ranking works, what it picked, everything it rejected and
why, then the parts of the model that are weaker than they look.
"""

from __future__ import annotations

from .model import api_delta, buy_fee_bps, roi_of
from .records import TokenMetrics
from .results import FIXTURE_BANNER, RunResult
from .selection import cap_bps, floor_bps

FLAG_LEGEND = {
    "high_volume": "top-quartile 30-day volume",
    "thin_liquidity": "top-quartile turnover (V30/L)",
    "dead": "no 7-day volume, or depth below the floor",
    "no_feed": "no Standard Chainlink feed",
    "multiplier": "uiMultiplier() != 1 (corporate action in effect)",
    "insufficient_history": "too few daily prices for a volatility estimate",
    "unpriced": "no USD price could be derived",
    "api_delta": "chain volume disagrees with the aggregators by >40%",
}


def usd(value: float | None) -> str:
    """Compact USD."""
    if value is None:
        return "-"
    if value >= 1_000_000_000:
        return f"${value / 1e9:.2f}B"
    if value >= 1_000_000:
        return f"${value / 1e6:.2f}M"
    if value >= 1_000:
        return f"${value / 1e3:.1f}k"
    if value <= 0:
        return "$0"
    return f"${value:,.2f}" if value < 10 else f"${value:,.0f}"


def pct(value: float | None, digits: int = 2) -> str:
    """Percentage from a ratio, without `-0%`."""
    if value is None:
        return "-"
    scaled = value * 100
    if abs(scaled) < 0.5 * 10**-digits:
        scaled = 0.0
    return f"{scaled:.{digits}f}%"


def share_pct(value: float | None) -> str:
    """Capturable share, which spans four orders of magnitude across a real universe."""
    if value is None:
        return "-"
    scaled = value * 100
    if scaled >= 1:
        return f"{scaled:.2f}%"
    if scaled >= 0.01:
        return f"{scaled:.3f}%"
    return f"{scaled:.4f}%"


def _flags(record: TokenMetrics) -> str:
    return ", ".join(sorted(record.flags)) or "-"


def _feed_cell(record: TokenMetrics) -> str:
    feed = record.feed
    if feed is None:
        return "none"
    heartbeat = f"{feed.heartbeat_seconds}s" if feed.heartbeat_seconds else "?"
    return f"`{feed.proxy[:10]}…` / {heartbeat}"


def render(result: RunResult) -> str:
    """The full report."""
    lines: list[str] = []
    add = lines.append

    add("# Amplestocks launch constituents")
    add("")
    if result.is_fixture:
        add(f"> **{FIXTURE_BANNER}.**")
        add(">")
        add(
            "> This document was produced by the `--fixtures` run, which replays a synthetic "
            "cassette generated by `packages/quant/tools/generate_fixtures.py`. Every ticker, "
            "address, price and volume below is invented to exercise the pipeline. It exists so "
            "the shape of the real output — and the reasoning that produces it — can be reviewed "
            "before the hosts in §10 are reachable. **Do not deploy anything from this file.**"
        )
        add(">")
        add(
            f"> The cassette holds {len(result.metrics)} synthetic tokens, so the recorded run "
            f"selects {result.params.count} rather than 30. The real run takes the default "
            "`--count 30` against the ~90-name Robinhood Stock Token universe; nothing else about "
            "the command changes."
        )
        add("")
    add(
        "How the 30 launch spokes are chosen: rank every Robinhood Stock Token by the fee revenue "
        "Amplestocks' protocol-owned liquidity would earn per dollar placed, drop what cannot be "
        "registered, and keep enough deep names to make rotation work."
    )
    add("")
    _provenance(add, result)
    _methodology(add, result)
    _chosen(add, result)
    _ranking(add, result)
    _placements(add, result)
    _rejected(add, result)
    _inclusion(add, result)
    _crosscheck(add, result)
    _caveats(add, result)
    _sources(add, result)
    _rerun(add, result)
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------------------------------------
# Sections
# ------------------------------------------------------------------------------------------------


def _provenance(add, result: RunResult) -> None:
    params = result.params
    add("## 1. What this run measured")
    add("")
    add("| | |")
    add("|---|---|")
    add(f"| Data timestamp (head block time) | {result.iso()} |")
    add(f"| Report generated | {result.iso(result.generated_at)} |")
    add("| Chain | Robinhood Chain 4663 |")
    add(
        f"| Window | {params.window_days} days (`V30`), {params.short_window_days} days (`V7`); "
        f"blocks {result.window_from_block:,} → {result.head_block:,} |"
    )
    add(f"| Tokens measured | {len(result.metrics)} |")
    add(f"| Pools measured | {sum(len(m.markets) for m in result.metrics)} |")
    add(f"| Placement `P` | ${params.placement:,.0f} (also computed at " + ", ".join(f"${p:,.0f}" for p in params.placements[1:]) + ") |")
    add(f"| Fee basis for ranking | `{params.fee_basis}` |")
    add(f"| RPC requests | {result.rpc_requests:,} ({result.log_requests:,} `eth_getLogs`) |")
    add(f"| Mode | {'FIXTURE (no network)' if result.is_fixture else 'live chain read'} |")
    add("")
    if result.warnings:
        add("**Warnings raised during the run:**")
        add("")
        for warning in result.warnings:
            add(f"- {warning}")
        add("")


def _methodology(add, result: RunResult) -> None:
    params = result.params
    add("## 2. Methodology")
    add("")
    add("For each stock token, aggregated over every v4 and v3 pool that has it on one side:")
    add("")
    add("```")
    add("V7, V30  USD volume over the 7- and 30-day windows, from Swap events, quote leg only")
    add("L        USD depth within +/-2% of price, from getSlot0/getLiquidity at head")
    add("P        Amplestocks' placement in that spoke                (--placement)")
    add("s        = P / (L + P)                                       capturable share")
    add("f        = 5 bp (SPOKE) or 10 bp (SPOKE_HIGH_VOL)            the fee we charge")
    add("R        = (V30 / 30) * s * f                                USD fee revenue per day")
    add("ROI      = R * 365 / P                                       annualised, on placed capital")
    add("```")
    add("")
    add(
        "`s` is proportional-share: a marginal dollar of in-range liquidity earns fees in "
        "proportion to its share of what is quotable at the touch. It ranks names correctly and "
        "over-states revenue — see §9."
    )
    add("")
    add(
        f"**Volume** is the quote leg (USDG/USDC at ${params.usdg_usd:.2f}, WETH at the WETH/stable "
        "pool price), so a swap is counted once. **Price** comes from `sqrtPriceX96` on the swap, "
        "not from the amounts, so fees and slippage do not bias it. **Depth** is the standard "
        "constant-liquidity band estimator: `amount1 = L*(sqrt(P_hi) - sqrt(P))`, "
        "`amount0 = L*(1/sqrt(P_lo) - 1/sqrt(P))`, both priced and summed."
    )
    add("")
    add("**Filters and flags.**")
    add("")
    for flag, meaning in FLAG_LEGEND.items():
        add(f"- `{flag}` — {meaning}")
    add("")
    add(
        f"`dead` (V7 = 0 or L < ${params.dead_depth_usd:,.0f}) and `no_feed` are hard drops. "
        "Quartiles are measured over the live, feed-having population only."
    )
    add("")
    quartiles = result.quartiles
    if quartiles:
        add(
            f"This run's cut-offs: top-volume quartile at {usd(quartiles.get('volume_p75'))} of "
            f"30-day volume, top-turnover quartile at {quartiles.get('turnover_p75', 0):.2f}x/day, "
            f"over a live population of {int(quartiles.get('population', 0))}."
        )
        add("")
    n = max(1, len(result.selection.chosen))
    add(
        f"**Weights.** `sqrt(V30 * L)`, clamped into the registry's own band for n = {n} "
        f"(`cap_n` = {cap_bps(n):,} bp, `floor_n` = {floor_bps(n):,} bp) and normalised to exactly "
        "10,000 bp. Rollout weights equal target weights. **Buy-fee bucket:** 10 bp when 30-day "
        f"realised volatility exceeds {params.vol_threshold * 100:.0f}%, else 5 bp. **Tick "
        f"spacing:** the token's most common v4 spacing, else {params.default_tick_spacing}."
    )
    add("")


def _chosen(add, result: RunResult) -> None:
    add(f"## 3. The launch set ({len(result.selection.chosen)} names)")
    add("")
    if result.selection.shortfall:
        add(
            f"> **Short by {result.selection.shortfall}.** Only {len(result.selection.chosen)} names "
            f"cleared the filters against a target of {result.params.count}."
        )
        add("")
    add("| # | Symbol | Weight bp | Fee | Class | Tick | Feed | Why |")
    add("|---:|---|---:|---:|---|---:|---|---|")
    for c in result.selection.chosen:
        add(
            f"| {c.rank} | **{c.metrics.symbol}** | {c.target_weight_bps} | {c.buy_fee_bps} bp | "
            f"{c.pool_class} | {c.metrics.tick_spacing} | {_feed_cell(c.metrics)} | {c.rationale} |"
        )
    add("")
    thin = [c.metrics.symbol for c in result.selection.chosen if "thin_liquidity" in c.metrics.flags]
    deep = [c.metrics.symbol for c in result.selection.chosen if "high_volume" in c.metrics.flags]
    add(
        f"**Thin-liquidity picks ({len(thin)}):** {', '.join(thin) or 'none'} — these are the "
        "share-capture names; their ROI comes from `s`, not from flow, and it decays as soon as "
        "anyone else provides depth."
    )
    add("")
    population = int(result.quartiles.get("population", 0))
    available = sum(1 for m in result.metrics if "high_volume" in m.flags)
    add(
        f"**High-volume picks ({len(deep)}):** {', '.join(deep) or 'none'} — the rotation-depth "
        f"floor is {result.params.min_high_volume}."
    )
    if available < result.params.min_high_volume:
        add("")
        add(
            f"> The floor could not bind: only {available} name(s) are in the top-volume quartile "
            f"of a live population of {population}, and the rule cannot promote names that do not "
            "exist. At the real universe size the quartile is much larger; if it stays smaller "
            "than `--min-high-volume`, lower the floor rather than widening the quartile."
        )
    add("")
    for note in result.selection.notes:
        add(f"- {note}")
    if result.selection.notes:
        add("")


def _ranking(add, result: RunResult) -> None:
    params = result.params
    add("## 4. Full ranking")
    add("")
    add(
        "Every token the universe collectors returned, ordered by ROI at "
        f"${params.placement:,.0f}. `R` and `ROI` use the `{params.fee_basis}` fee basis; the "
        "effective-fee column shows what the token's existing pools charge today."
    )
    add("")
    add("| Symbol | Pools | V7 | V30 | L (±2%) | Turnover | s | R $/day | ROI | σ | Fee bp | Eff bp | Feed | Flags |")
    add("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|---|")
    chosen = {c.metrics.symbol for c in result.selection.chosen}
    ordered = sorted(result.metrics, key=lambda m: (-roi_of(m, params), -m.volume_usd_30d, m.symbol))
    for record in ordered:
        score = record.scores.get(params.placement)
        mark = "**" if record.symbol in chosen else ""
        turnover = f"{record.turnover:.2f}x" if record.turnover is not None else "-"
        sigma = pct(record.realised_vol_annual, 0) if record.realised_vol_annual is not None else "-"
        effective = f"{record.effective_fee_bps:.1f}" if record.effective_fee_bps is not None else "-"
        add(
            f"| {mark}{record.symbol}{mark} | {len(record.markets)} | {usd(record.volume_usd_7d)} | "
            f"{usd(record.volume_usd_30d)} | {usd(record.depth_usd_2pct)} | {turnover} | "
            f"{share_pct(score.capturable_share if score else None)} | "
            f"{usd(score.revenue_usd_day_base if score else None)} | "
            f"{pct(roi_of(record, params), 1)} | {sigma} | {buy_fee_bps(record, params):.0f} | "
            f"{effective} | {_feed_cell(record)} | {_flags(record)} |"
        )
    add("")
    add("Bold = selected.")
    add("")


def _placements(add, result: RunResult) -> None:
    params = result.params
    if len(params.placements) < 2:
        return
    add("## 5. Placement sensitivity")
    add("")
    add(
        "The same names at each placement size. ROI falls as `P` grows because `s = P / (L + P)` "
        "is concave: the second dollar into a thin book earns less than the first."
    )
    add("")
    header = " | ".join(f"ROI @ ${p:,.0f}" for p in params.placements)
    add(f"| Symbol | L (±2%) | {header} |")
    add("|---|---:|" + "---:|" * len(params.placements))
    for c in result.selection.chosen:
        record = c.metrics
        cells = []
        for placement in params.placements:
            score = record.scores.get(placement)
            value = (
                (score.roi_effective if params.fee_basis == "effective" else score.roi_base)
                if score
                else None
            )
            cells.append(pct(value, 1))
        add(f"| {record.symbol} | {usd(record.depth_usd_2pct)} | " + " | ".join(cells) + " |")
    add("")


def _rejected(add, result: RunResult) -> None:
    add("## 6. Rejected")
    add("")
    by_reason: dict[str, list[str]] = {}
    for rejection in result.selection.rejected:
        by_reason.setdefault(rejection.reason, []).append(f"{rejection.symbol} ({rejection.detail})")
    if not by_reason:
        add("Nothing was rejected: every measured name cleared the filters and fitted in the set.")
        add("")
        return
    add("| Reason | Names |")
    add("|---|---|")
    labels = {
        "no_feed": "No Standard Chainlink feed — cannot be registered",
        "dead": "Dead: no 7-day volume or no depth",
        "displaced": "Displaced by the rotation-depth rule",
        "rank": "Ranked below the cut",
    }
    for reason, names in by_reason.items():
        add(f"| {labels.get(reason, reason)} | {'; '.join(names)} |")
    add("")


def _inclusion(add, result: RunResult) -> None:
    if not result.inclusion:
        return
    add("## 7. Inclusion evidence")
    add("")
    add(
        "`PoolRegistry` stores `InclusionRecord{betaX18, trackingErrorX18, indexVolX18, "
        "historyDays}` and, whenever `rolloutWeightBps != 0`, enforces "
        "`beta > 0.5 + TE^2 / (2 * indexVol^2)` and `historyDays >= 30`. Beta is measured against "
        "the equal-weighted daily return of the selected set over this window."
    )
    add("")
    add("| Symbol | β | Tracking error | Index vol | History days | Rule | Note |")
    add("|---|---:|---:|---:|---:|---|---|")
    for c in result.selection.chosen:
        stats = result.inclusion.get(c.metrics.symbol)
        if stats is None:
            continue
        verdict = stats.passes()
        add(
            f"| {c.metrics.symbol} | {stats.beta:.3f} | {pct(stats.tracking_error, 1)} | "
            f"{pct(stats.index_vol, 1)} | {stats.history_days} | "
            f"{'pass' if verdict else ('fail' if verdict is False else 'not measured')} | "
            f"{stats.note or '-'} |"
            if stats.measured
            else f"| {c.metrics.symbol} | - | - | - | {stats.history_days} | not measured | {stats.note or '-'} |"
        )
    add("")
    short = [
        c.metrics.symbol
        for c in result.selection.chosen
        if (result.inclusion.get(c.metrics.symbol) or None) and result.inclusion[c.metrics.symbol].history_days < 30
    ]
    if short:
        add(
            f"**{len(short)} name(s) carry fewer than 30 observed days** "
            f"({', '.join(short[:8])}{'…' if len(short) > 8 else ''}). `MIN_HISTORY_DAYS` is 30, and a "
            f"{result.params.window_days}-day window can evidence at most {result.params.window_days}; "
            "run with `--window 45` or supply the Phase 0A equity history before registration."
        )
        add("")


def _crosscheck(add, result: RunResult) -> None:
    rows = [(m, api_delta(m)) for m in result.metrics if m.api_quotes]
    add("## 8. Chain vs aggregators")
    add("")
    if not rows:
        add(
            "No aggregator answered in this run (`--no-cross-check`, or every endpoint refused). "
            "Chain figures stand alone."
        )
        add("")
        return
    add(
        "Chain data is authoritative. These are the aggregators' own 24 h volume and reserve for "
        "the same tokens, and the gap against this run's `V30/30`."
    )
    add("")
    add("| Symbol | Chain $/day | GeckoTerminal 24h | DexPaprika 24h | DexScreener 24h | Reserve (median) | Δ |")
    add("|---|---:|---:|---:|---:|---:|---:|")
    for record, delta in sorted(rows, key=lambda r: -r[0].volume_usd_30d):
        quotes = {q.source: q for q in record.api_quotes}
        reserves = sorted(q.reserve_usd for q in record.api_quotes if q.reserve_usd is not None)
        median_reserve = reserves[len(reserves) // 2] if reserves else None
        add(
            f"| {record.symbol} | {usd(record.volume_usd_30d / 30)} | "
            f"{usd(quotes['geckoterminal'].volume_usd_24h) if 'geckoterminal' in quotes else '-'} | "
            f"{usd(quotes['dexpaprika'].volume_usd_24h) if 'dexpaprika' in quotes else '-'} | "
            f"{usd(quotes['dexscreener'].volume_usd_24h) if 'dexscreener' in quotes else '-'} | "
            f"{usd(median_reserve)} | {pct(delta, 0) if delta is not None else '-'} |"
        )
    add("")


def _caveats(add, result: RunResult) -> None:
    params = result.params
    add("## 9. Caveats")
    add("")
    add(
        "1. **`R` is an upper bound, not a forecast.** The volume measured here is "
        "`<stock>/USDG` flow. An `AMPS/<stock>` spoke only sees a router when someone wants AMPS "
        "on the other side, or when an arbitrageur is closing a gap against NAV. Read `R` as "
        "*relative* attractiveness across names, and size the launch on the redemption floor, not "
        "on this number."
    )
    add(
        "2. **Depth is a snapshot, volume is a window.** `L` is read at head; a book that emptied "
        "yesterday still shows yesterday's volume against today's thin depth and scores too well. "
        "The `thin_liquidity` flag is exactly where this bites hardest."
    )
    add(
        "3. **The ±2% depth figure assumes constant liquidity across the band.** Where a tight "
        "range sits just outside the current tick, real depth is larger than reported; where the "
        "active range ends inside the band, it is smaller."
    )
    add(
        "4. **`uiMultiplier() != 1` means a corporate action is in effect.** A split or spin-off "
        "changes what one token is a claim on. Names carrying the `multiplier` flag need the "
        "vault's corporate-action path exercised on 46630 before they are registered."
    )
    add(
        "5. **SVR feeds are not Standard feeds.** Only non-SVR equity feeds count towards "
        "`no_feed`. If a ticker exists only as SVR, it is rejected here even though a feed "
        "address exists — `FeedRegistry.setStandardProxy` is the wrong call for it."
    )
    add(
        "6. **Pools that appeared mid-window are under-counted.** A pool created on day 25 of a "
        "30-day window contributes 5 days of volume against a 30-day denominator, so its `V30/30` "
        "understates its current run-rate. The per-pool `firstSwapTs` in "
        "`packages/quant/out/constituents.json` is how to spot them."
    )
    add(
        "7. **Block timestamps inside the window are interpolated.** `eth_getLogs` returns no "
        "timestamps and a 30-day window is ~26 M blocks on a 100 ms chain; only the window "
        "boundaries are read exactly. This affects which UTC day a price sample lands in, and so "
        "the volatility and beta estimates, by at most the chain's block-time drift."
    )
    add(
        f"8. **Placement `P` is a parameter, and the repo disagrees with it.** This run ranks at "
        f"${params.placement:,.0f}. `packages/config/src/index.ts` "
        "(`launchParameters.supply.perSpokeSeedAmps`) puts the per-spoke seed at 47.5 AMPS — "
        "$47.50 at the $1.00 genesis floor — from a 5,000 AMPS supply with a 95% POL tranche. The "
        "$300 default comes from the brief's 20,000 AMPS / 45%-tranche variant. Ranking is almost "
        "unaffected (`s` is monotone in `P`, and ordering only moves where two names' depths "
        "straddle `P`), but every ROI figure scales with the choice. Settle the supply number "
        "before quoting these ROIs anywhere."
    )
    if result.is_fixture:
        add(
            "9. **This document is fixture output.** Nothing in §3-§8 is a market observation."
        )
    add("")


def _sources(add, result: RunResult) -> None:
    add("## 10. Provenance")
    add("")
    add("| Collector | Source | OK | Items | Note |")
    add("|---|---|---|---:|---|")
    for source in result.sources:
        add(
            f"| {source.collector} | {source.source} | {'yes' if source.ok else 'NO'} | "
            f"{source.items} | {source.note or '-'} |"
        )
    add("")
    add("Hosts this pipeline dials:")
    add("")
    for host in result.hosts:
        add(f"- `{host}`")
    add("")


def _rerun(add, result: RunResult) -> None:
    params = result.params
    add("## 11. Reproducing this")
    add("")
    add("```bash")
    add("cd packages/quant")
    add("python3 -m venv .venv && . .venv/bin/activate && pip install -e '.[dev]'")
    add("")
    add("# the run that produced this document")
    if result.is_fixture:
        add(f"python -m amplestocks_quant.constituents run --fixtures --count {params.count} --out out")
    else:
        add("python -m amplestocks_quant.constituents run \\")
        add(f"  --rpc {params.rpc_url} \\")
        add(f"  --window {params.window_days} --placement {params.placement:g} \\")
        add(f"  --count {params.count} --out out")
    add("```")
    add("")
    add(
        "Outputs: `out/constituents.json` (this ranking as data), `out/launch-set.ts` (paste "
        "source for `packages/config/src/index.ts`), `out/constituents.registry.json` (the "
        "`contracts/script/config/constituents.json` shape) and this file. See "
        "`packages/quant/README.md` §Runbook."
    )
    add("")
