# SPDX-License-Identifier: MIT
"""Transports: one real (urllib), one that replays a recorded fixture cassette.

Every collector in this package reaches the network through a `Transport`, never through `urllib`
directly. That is what makes the whole pipeline runnable — and unit-testable — with no egress: the
`--fixtures` run swaps `HttpTransport` for `FixtureTransport` and nothing else changes.

The fixture cassette is a single JSON file (`fixtures/cassette.json`) holding:

* `chain` — head block, head timestamp and block time, from which block headers are synthesised;
* `text` / `json` — recorded HTTP bodies keyed by URL;
* `logs` — a flat list of `eth_getLogs` results, filtered by range/address/topics on replay;
* `calls` — `eth_call` return data keyed by `<to>:<calldata>`;
* `storage` — `eth_getStorageAt` values keyed by `<address>:<slot>`.

**The committed cassette is synthetic.** It is generated by `tools/generate_fixtures.py` from a
seeded PRNG and contains no market data; see that file and the `$comment` in the cassette.
"""

from __future__ import annotations

import gzip
import json
import time
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Protocol

DEFAULT_TIMEOUT = 30.0
DEFAULT_RETRIES = 3
USER_AGENT = "amplestocks-quant/constituents (+https://github.com/amplestocks)"


class TransportError(RuntimeError):
    """A request failed after every retry, or the fixture cassette has no answer for it."""


class Transport(Protocol):
    """The surface every collector is allowed to use."""

    def get_json(self, url: str, *, headers: dict[str, str] | None = None) -> Any:
        """GET `url` and parse the body as JSON."""

    def get_text(self, url: str, *, headers: dict[str, str] | None = None) -> str:
        """GET `url` and return the body as text."""

    def post_json(self, url: str, payload: Any, *, headers: dict[str, str] | None = None) -> Any:
        """POST `payload` as JSON to `url` and parse the response as JSON."""


# ------------------------------------------------------------------------------------------------
# Real transport
# ------------------------------------------------------------------------------------------------


@dataclass
class HttpTransport:
    """`urllib`-backed transport with retries and exponential backoff.

    Deliberately dependency-free: a launch-set run has to work from a clean `python3` on an
    operator's laptop, and adding `requests`/`httpx` to `pyproject.toml` for six GETs is not worth
    the supply-chain surface.
    """

    timeout: float = DEFAULT_TIMEOUT
    retries: int = DEFAULT_RETRIES
    backoff: float = 0.75
    #: Every URL this transport has touched, in order — copied into the report's provenance block.
    calls: list[str] = field(default_factory=list)

    def _request(self, url: str, data: bytes | None, headers: dict[str, str] | None) -> bytes:
        merged = {
            "User-Agent": USER_AGENT,
            "Accept": "application/json, text/html;q=0.9, */*;q=0.5",
            "Accept-Encoding": "gzip, identity",
        }
        if data is not None:
            merged["Content-Type"] = "application/json"
        merged.update(headers or {})
        self.calls.append(url)

        last: Exception | None = None
        for attempt in range(self.retries):
            request = urllib.request.Request(url, data=data, headers=merged)
            try:
                with urllib.request.urlopen(request, timeout=self.timeout) as response:
                    body = response.read()
                    if response.headers.get("Content-Encoding") == "gzip":
                        body = gzip.decompress(body)
                    return body
            except urllib.error.HTTPError as exc:
                last = exc
                if exc.code in (400, 401, 403, 404, 405, 410):
                    break
            except (urllib.error.URLError, TimeoutError, OSError) as exc:
                last = exc
            if attempt + 1 < self.retries:
                time.sleep(self.backoff * (2**attempt))
        raise TransportError(f"{url}: {last}") from last

    def get_json(self, url: str, *, headers: dict[str, str] | None = None) -> Any:
        """GET `url` and parse the body as JSON."""
        return json.loads(self._request(url, None, headers))

    def get_text(self, url: str, *, headers: dict[str, str] | None = None) -> str:
        """GET `url` and return the body as text."""
        return self._request(url, None, headers).decode("utf-8", "replace")

    def post_json(self, url: str, payload: Any, *, headers: dict[str, str] | None = None) -> Any:
        """POST `payload` as JSON to `url` and parse the response as JSON."""
        body = json.dumps(payload).encode()
        return json.loads(self._request(url, body, headers))


# ------------------------------------------------------------------------------------------------
# Fixture transport
# ------------------------------------------------------------------------------------------------


def _hex(value: int) -> str:
    return hex(value)


def _as_int(value: Any, default: int) -> int:
    if value is None:
        return default
    if isinstance(value, int):
        return value
    text = str(value)
    if text in ("latest", "safe", "finalized", "pending", "earliest"):
        return default
    try:
        return int(text, 16) if text.startswith("0x") else int(text)
    except ValueError:
        return default


def _topics_match(log_topics: list[str], wanted: list[Any] | None) -> bool:
    """Ethereum `eth_getLogs` topic semantics: positional, `None` is a wildcard, a list is an OR."""
    if not wanted:
        return True
    for i, want in enumerate(wanted):
        if want is None:
            continue
        if i >= len(log_topics):
            return False
        options = want if isinstance(want, list) else [want]
        if not any(str(o).lower() == log_topics[i].lower() for o in options):
            return False
    return True


@dataclass
class FixtureTransport:
    """Replays a recorded cassette. Raises `TransportError` on anything it was not taught.

    Block headers are *synthesised* from `chain.headBlock`/`headTimestamp`/`blockTimeSeconds`
    rather than recorded, so a 30-day window over 100 ms blocks does not need 26 million headers in
    the fixture. That synthesis is part of why the cassette is labelled synthetic.
    """

    cassette: dict[str, Any]
    #: Requests the cassette could not answer, so a fixture run can report them instead of lying.
    misses: list[str] = field(default_factory=list)
    strict: bool = True
    calls: list[str] = field(default_factory=list)

    @classmethod
    def from_path(cls, path: str | Path, *, strict: bool = True) -> FixtureTransport:
        """Load a cassette from disk."""
        data = json.loads(Path(path).read_text())
        return cls(cassette=data, strict=strict)

    # -- HTTP ------------------------------------------------------------------------------------

    def _lookup(self, bucket: str, url: str) -> Any:
        entries: dict[str, Any] = self.cassette.get(bucket, {})
        if url in entries:
            return entries[url]
        # Case-insensitive, because a URL that embeds an address may carry it checksummed or
        # lowercased depending on which source supplied it, and every real API treats the two the
        # same. Also tolerates a templated URL recorded without its query string.
        wanted = url.lower()
        for key, value in entries.items():
            lowered = key.lower()
            if wanted == lowered or wanted.startswith(lowered) or lowered.startswith(wanted.split("?")[0]):
                return value
        self.misses.append(f"{bucket} {url}")
        raise TransportError(f"fixture cassette has no {bucket} entry for {url}")

    def get_json(self, url: str, *, headers: dict[str, str] | None = None) -> Any:
        """Recorded JSON body for `url`."""
        self.calls.append(url)
        return self._lookup("json", url)

    def get_text(self, url: str, *, headers: dict[str, str] | None = None) -> str:
        """Recorded text body for `url`."""
        self.calls.append(url)
        return str(self._lookup("text", url))

    # -- JSON-RPC --------------------------------------------------------------------------------

    def post_json(self, url: str, payload: Any, *, headers: dict[str, str] | None = None) -> Any:
        """Answer a single or batched JSON-RPC request out of the cassette."""
        self.calls.append(url)
        if isinstance(payload, list):
            return [self._rpc(item) for item in payload]
        return self._rpc(payload)

    def _rpc(self, request: dict[str, Any]) -> dict[str, Any]:
        method = request.get("method")
        params = request.get("params") or []
        rid = request.get("id", 1)
        try:
            result = self._dispatch(method, params)
        except TransportError:
            # An `eth_call` the cassette does not know about is the fixture equivalent of a revert,
            # which is a normal answer a collector must handle — not a broken fixture. Every other
            # unknown request is a hole in the cassette and is raised under `strict`.
            if method == "eth_call" or not self.strict:
                return {
                    "jsonrpc": "2.0",
                    "id": rid,
                    "error": {"code": 3, "message": "execution reverted (no fixture entry)"},
                }
            raise
        return {"jsonrpc": "2.0", "id": rid, "result": result}

    def _dispatch(self, method: str | None, params: list[Any]) -> Any:
        chain = self.cassette.get("chain", {})
        head = int(chain.get("headBlock", 0))
        head_ts = int(chain.get("headTimestamp", 0))
        block_time = float(chain.get("blockTimeSeconds", 0.1))

        if method == "eth_chainId":
            return _hex(int(chain.get("chainId", 4663)))
        if method == "eth_blockNumber":
            return _hex(head)
        if method == "eth_getBlockByNumber":
            number = _as_int(params[0] if params else "latest", head)
            number = max(0, min(number, head))
            timestamp = head_ts - round((head - number) * block_time)
            return {"number": _hex(number), "timestamp": _hex(timestamp), "hash": "0x" + "11" * 32}
        if method == "eth_getLogs":
            return self._logs(params[0] if params else {})
        if method == "eth_call":
            call = params[0] if params else {}
            key = f"{str(call.get('to', '')).lower()}:{str(call.get('data', '')).lower()}"
            calls: dict[str, str] = self.cassette.get("calls", {})
            if key in calls:
                return calls[key]
            self.misses.append(f"eth_call {key}")
            raise TransportError(f"fixture cassette has no eth_call entry for {key}")
        if method == "eth_getStorageAt":
            key = f"{str(params[0]).lower()}:{str(params[1]).lower()}"
            storage: dict[str, str] = self.cassette.get("storage", {})
            if key in storage:
                return storage[key]
            return "0x" + "00" * 32
        self.misses.append(f"rpc {method}")
        raise TransportError(f"fixture cassette does not implement {method}")

    def _logs(self, flt: dict[str, Any]) -> list[dict[str, Any]]:
        head = int(self.cassette.get("chain", {}).get("headBlock", 0))
        lo = _as_int(flt.get("fromBlock"), 0)
        hi = _as_int(flt.get("toBlock"), head)
        addresses = flt.get("address")
        if isinstance(addresses, str):
            addresses = [addresses]
        wanted = {a.lower() for a in addresses} if addresses else None
        topics = flt.get("topics")

        out = []
        for log in self.cassette.get("logs", []):
            number = _as_int(log.get("blockNumber"), 0)
            if number < lo or number > hi:
                continue
            if wanted is not None and str(log.get("address", "")).lower() not in wanted:
                continue
            if not _topics_match([str(t) for t in log.get("topics", [])], topics):
                continue
            out.append(log)
        return out
